declare const ACTIVATE_GUEST_API = "https://api.twitter.com/1.1/guest/activate.json";
declare const GET_USER_BY_SCREENAME = "https://twitter.com/i/api/graphql/G3KGOASz96M-Qu0nwmGXNg/UserByScreenName";
declare const GET_TWEETS_BY_USER_ID = "https://twitter.com/i/api/graphql/H8OOoI-5ZE4NxgRr8lfyWg/UserTweets";
declare const GET_TWEET_BY_ID = "https://twitter.com/i/api/graphql/DJS3BdhUhcaEpZ7B7irJDg/TweetResultByRestId";
declare const GET_FOLLOWERS_BY_USER_ID = "https://twitter.com/i/api/graphql/rRXFSG5vR6drKr5M37YOTw/Followers";
declare const GET_FOLLOWING_BY_USER_ID = "https://twitter.com/i/api/graphql/iSicc7LrzWGBgDPL0tM_TQ/Following";
declare const SEARCH_TIMELINE = "https://api.twitter.com/graphql/gkjsKepM6gl_HmFWoWKfgg/SearchTimeline";
declare const SEARCH_API = "https://twitter.com/i/api/2/search/adaptive.json";
declare const BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAFQODgEAAAAAVHTp76lzh3rFzcHbmHVvQxYYpTw%3DckAlMINMjmCwxUcaXbAN4XqJVdgMJaHqNOFgPMK0zN1qLqLQCF";
export { ACTIVATE_GUEST_API, GET_TWEET_BY_ID, GET_TWEETS_BY_USER_ID, GET_USER_BY_SCREENAME, GET_FOLLOWERS_BY_USER_ID, GET_FOLLOWING_BY_USER_ID, SEARCH_TIMELINE, SEARCH_API, BEARER_TOKEN };
