"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BEARER_TOKEN = exports.SEARCH_API = exports.SEARCH_TIMELINE = exports.GET_FOLLOWING_BY_USER_ID = exports.GET_FOLLOWERS_BY_USER_ID = exports.GET_USER_BY_SCREENAME = exports.GET_TWEETS_BY_USER_ID = exports.GET_TWEET_BY_ID = exports.ACTIVATE_GUEST_API = void 0;
const ACTIVATE_GUEST_API = 'https://api.twitter.com/1.1/guest/activate.json';
exports.ACTIVATE_GUEST_API = ACTIVATE_GUEST_API;
const GET_USER_BY_SCREENAME = 'https://twitter.com/i/api/graphql/G3KGOASz96M-Qu0nwmGXNg/UserByScreenName';
exports.GET_USER_BY_SCREENAME = GET_USER_BY_SCREENAME;
const GET_TWEETS_BY_USER_ID = 'https://twitter.com/i/api/graphql/H8OOoI-5ZE4NxgRr8lfyWg/UserTweets';
exports.GET_TWEETS_BY_USER_ID = GET_TWEETS_BY_USER_ID;
const GET_TWEET_BY_ID = 'https://twitter.com/i/api/graphql/DJS3BdhUhcaEpZ7B7irJDg/TweetResultByRestId';
exports.GET_TWEET_BY_ID = GET_TWEET_BY_ID;
const GET_FOLLOWERS_BY_USER_ID = 'https://twitter.com/i/api/graphql/rRXFSG5vR6drKr5M37YOTw/Followers';
exports.GET_FOLLOWERS_BY_USER_ID = GET_FOLLOWERS_BY_USER_ID;
const GET_FOLLOWING_BY_USER_ID = 'https://twitter.com/i/api/graphql/iSicc7LrzWGBgDPL0tM_TQ/Following';
exports.GET_FOLLOWING_BY_USER_ID = GET_FOLLOWING_BY_USER_ID;
const SEARCH_TIMELINE = 'https://api.twitter.com/graphql/gkjsKepM6gl_HmFWoWKfgg/SearchTimeline';
exports.SEARCH_TIMELINE = SEARCH_TIMELINE;
const SEARCH_API = 'https://twitter.com/i/api/2/search/adaptive.json';
exports.SEARCH_API = SEARCH_API;
const BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAFQODgEAAAAAVHTp76lzh3rFzcHbmHVvQxYYpTw%3DckAlMINMjmCwxUcaXbAN4XqJVdgMJaHqNOFgPMK0zN1qLqLQCF';
exports.BEARER_TOKEN = BEARER_TOKEN;
